### ISSUE TITLE
jupyterlab AttributeError: 'NotebookWebApplication' object has no attribute 'append'

### ISSUE THREAD

**Issue by robnagler** [radiasoft/container-beamsim-jupyter-base#33]
NotebookWebApplication doesn't support "append". Need to review history to see what version works...

```txt
[I 23:36:07.049 LabApp] JupyterLab application directory is /home/vagrant/.pyenv/versions/3.7.2/envs/py3/share/jupyter/lab
[W 23:36:07.051 LabApp] Error loading server extension jupyterlab
    Traceback (most recent call last):
      File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/notebook/notebookapp.py", line 1991, in init_server_extensions
        func(self)
      File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/jupyterlab/extension.py", line 222, in load_jupyter_server_extension
        add_handlers(web_app, config)
      File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/jupyterlab_server/handlers.py", line 165, in add_handlers
        handlers.append((url_pattern, LabHandler))
    AttributeError: 'NotebookWebApplication' object has no attribute 'append'
```

**Comment by robnagler** [comment]
I suspect it's related to not upgrading to jupyterlab 3.x. Here's my pip list:

```txt
jupyterlab                    2.1.0
jupyterlab-launcher           0.13.1
jupyterlab-pygments           0.1.2
jupyterlab-server             2.0.0
jupyterlab-widgets            1.0.0
```

We didn't have an explicit dependency for jupyterlab-server so it automatically upgraded to 2.0.0 even though it was incompatible with jupyterlab 2.x.

**Comment by robnagler** [comment]
This is a jupyterlab 3.x issue. They rewrote a lot of stuff and didn't have a constraint in setup.py for jupyterlab-server.
