### ISSUE TITLE
cookie_name has changed

### ISSUE THREAD

**Issue by robnagler** [radiasoft/container-beamsim-jupyter-base#4]
This may be related to jupyterhub/wrapspawner#11. Need to figure out changes in minor release (0.8) that cause this error:

```text
/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/traitlets/config/configurable.py:84: UserWarning: Config option `cookie_name` not recognized by `HubOAuth`.
  self.config = config
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'oauth_client_id'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/jupyter/bin/jupyterhub-singleuser", line 6, in <module>
    main()
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/jupyterhub/singleuser.py", line 455, in main
    return SingleUserNotebookApp.launch_instance(argv)
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/notebook/notebookapp.py", line 1364, in initialize
    self.init_webapp()
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/jupyterhub/singleuser.py", line 393, in init_webapp
    self.init_hub_auth()
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/jupyterhub/singleuser.py", line 388, in init_hub_auth
    if not self.hub_auth.oauth_client_id:
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/traitlets/traitlets.py", line 593, in _validate
    value = self._cross_validate(obj, value)
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/traitlets/traitlets.py", line 599, in _cross_validate
    value = obj._trait_validators[self.name](obj, proposal)
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/traitlets/traitlets.py", line 907, in __call__
    return self.func(*args, **kwargs)
  File "/home/vagrant/.pyenv/versions/3.5.2/envs/jupyter/lib/python3.5/site-packages/jupyterhub/services/auth.py", line 439, in _ensure_not_empty
    raise ValueError("%s cannot be empty." % p
```

**Comment by robnagler** [comment]
We are probably past this. I had put in some fixes in the image.
