### ISSUE TITLE
f36 error with jupyter lab build --dev-build=False

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/container-beamsim-jupyter-base#81]
```
#0 221.6 $ webpack --config webpack.prod.minimize.config.js
#0 221.6 node:internal/crypto/hash:71
#0 221.6   this[kHandle] = new _Hash(algorithm, xofLen);
#0 221.6                   ^
#0 221.6
#0 221.6 Error: error:0308010C:digital envelope routines::unsupported
#0 221.6     at new Hash (node:internal/crypto/hash:71:19)
#0 221.6     at Object.createHash (node:crypto:130:10)
#0 221.6     at BulkUpdateDecorator.hashFactory (/home/vagrant/.pyenv/versions/3.9.15/envs/py3/share/jupyter/lab/staging/node_modules/webpack/lib/util/createHash.js:155:18)
#0 221.6     at BulkUpdateDecorator.update (/home/vagrant/.pyenv/versions/3.9.15/envs/py3/share/jupyter/lab/staging/node_modules/webpack/lib/util/createHash.js:46:50)
#0 221.6     at OriginalSource.updateHash (/home/vagrant/.pyenv/versions/3.9.15/envs/py3/share/jupyter/lab/staging/node_modules/webpack/node_modules/webpack-sources/lib/OriginalSource.js:131:8)
#0 221.6     at NormalModule._initBuildHash (/home/vagrant/.pyenv/versions/3.9.15/envs/py3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModule.js:888:17)on vega-lite
#0 221.6     at handleParseResult (/home/vagrant/.pyenv/versions/3.9.15/envs/py3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModule.js:954:10)
#0 221.6     at /home/vagrant/.pyenv/versions/3.9.15/envs/py3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModule.js:1048:4
#0 221.6     at processResult (/home/vagrant/.pyenv/versions/3.9.15/envs/py3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModule.js:763:11)no-build "${l[@]}"
#0 221.6     at /home/vagrant/.pyenv/versions/3.9.15/envs/py3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModule.js:827:5 {ab.readthedocs.io/en/stable/user/jupyterhub.html#use-jupyterlab-by-default
#0 221.6   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
#0 221.6   library: 'digital envelope routines',
#0 221.6   reason: 'unsupported',
#0 221.6   code: 'ERR_OSSL_EVP_UNSUPPORTED'
#0 221.6 }
#0 221.6 error Command failed with exit code 1
```

People have reported the issue on on node 17 https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported .

One person reported an issue with f36 on node 16 https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported#comment128002554_69746937 

We could try upgrading to node 17 and see if that works. Or use the `NODE_OPTIONS=--openssl-legacy-provider`. My concern with the flag is we could run into this bug further downstream.

**Comment by e-carlin** [comment]
Nodejs 17 isn't available on f36. So node 18 I think is the best option.

**Comment by e-carlin** [comment]
Welp tried with nodejs 18 and ran into the same issue. Setting NODE_OPTIONS it is...
